//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoLab5.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoLab5.API.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student created successfully!.
        /// </summary>
        internal static string Create_student {
            get {
                return ResourceManager.GetString("Create student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher created successfully!.
        /// </summary>
        internal static string Create_teacher {
            get {
                return ResourceManager.GetString("Create teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course created successfully!.
        /// </summary>
        internal static string CreateCourse {
            get {
                return ResourceManager.GetString("CreateCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All courses fetched successfully!.
        /// </summary>
        internal static string GetAllCourses {
            get {
                return ResourceManager.GetString("GetAllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is not valid..
        /// </summary>
        internal static string Invalid_data {
            get {
                return ResourceManager.GetString("Invalid data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong..
        /// </summary>
        internal static string Something_wrong {
            get {
                return ResourceManager.GetString("Something wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success In English.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course has been updated successfully!.
        /// </summary>
        internal static string Update_course {
            get {
                return ResourceManager.GetString("Update course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The picture has been updated successfully!.
        /// </summary>
        internal static string Update_pic {
            get {
                return ResourceManager.GetString("Update pic", resourceCulture);
            }
        }
    }
}
